const types = {
    AUTH_ERROR:'AUTH_ERROR',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    LOGIN_SIGNUP_SUCCESS:' LOGIN_SIGNUP_SUCCESS',
    CHANGE_PASSWORD_SUCCESS:'CHANGE_PASSWORD_SUCCESS',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    LOGOUT:'LOGOUT',
    DELETE_ACCOUNT_SUCCESS:'DELETE_ACCOUNT',
    REMOVE_ERRORS:'REMOVE_ERRORS',
    REMOVE_MESSAGES:'REMOVE_MESSAGES',
    CHECK_FIRST_LAUNCH:'CHECK_FIRST_LAUNCH',
  };
  
  export default types;